version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
     image: postgres
     volumes:
       - ./data/db:/var/lib/postgresql/data
     container_name: postgres_db
      
  # # Celery
  # celery:
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A core worker -l DEBUG
  #   volumes:
  #     - .:/django
  #   container_name: celery
  #   depends_on:
  #     - db
  #     - redis
  #     - app
