version: '3.8'
services:
  django:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: django:mine
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
       - djangonetwork
 
  db:
    image: postgres:13.4-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    networks:
      - djangonetwork
  

networks:
     djangonetwork:
         driver: bridge